config/routes.rb
YmRailsTemplate::Application.routes.draw do
  get "home/index"

  devise_for :users

  root :to => "home#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope :order => 'created_at ASC'

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :oauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
%h1 Home#index Dawg
%p Find me in app/views/home/index.html.haml

app/views/layouts/_flashes.html.haml
#flash
  - flash.each do |key, value|
    %div{ :title => key.to_s.humanize, :class => key }
      %p= value

app/views/layouts/_footer.html.haml
%small.copyright
  Copyright &copy; #{Date.today.year}

app/views/layouts/_head.html.haml
%head
  %meta{ :charset => "utf-8" }/
  
  -# 
    Always force latest IE rendering engine (even in intranet) & Chrome Frame
    Remove this if you use the .htaccess
  %meta{ :content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible" }/
  
  %title
    == #{ controller.controller_name.titleize } - #{ controller.action_name.titleize }
    
  %meta{ :content => "", :name => "description" }/
  %meta{ :content => "", :name => "author" }/
  
  -# Mobile viewport optimized: j.mp/bplateviewport
  %meta{ :content => "width=device-width; initial-scale=1.0", :name => "viewport" }/
  
  -# Place favicon.ico and apple-touch-icon.png in the root of your domain and delete these references
  -# %link{ :href => "/favicon.ico", :rel => "shortcut icon" }/
  -# %link{ :href => "/apple-touch-icon.png", :rel => "apple-touch-icon" }/
  
  = render :partial => 'layouts/stylesheets'
  
  -# All JavaScript at the bottom, except for Modernizr which enables HTML5 elements & feature detects
  = javascript_include_tag 'modernizr-1.5.min'
  
  = csrf_meta_tag

app/views/layouts/_header.html.haml
%h1 Header

app/views/layouts/_javascripts.html.haml
-# Grab Google CDN's jQuery
-# Looks for google_api_key first in ENV['GOOGLE_API_KEY'] then in config/google.yml
- if !google_api_key.blank?
  = javascript_include_tag "http://www.google.com/jsapi?key=#{google_api_key}"
  :javascript
    google.load("jquery", "1.4.2");
- else
  = javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"

-# fall back to local jQuery if necessary
:javascript
  !window.jQuery && document.write(unescape('%3Cscript src="/javascripts/jquery-1.4.2.min.js"%3E%3C/script%3E'))
  
= javascript_include_tag 'rails', 'plugins', 'application'

/[if lt IE 7 ]
  = javascript_include_tag 'dd_belatedpng'
  :javascript
    DD_belatedPNG.fix('img, .png_bg');
    
-#  Append your own using content_for :javascripts
= yield :javascripts

-# yui profiler and profileviewer
- if Rails.env == 'development'
  = javascript_include_tag 'profiling/yahoo-profiling.min', 'profiling/config'

-# asynchronous google analytics: mathiasbynens.be/notes/async-analytics-snippet
-# Looks for google_account_id first in ENV['GOOGLE_ACCOUNT_ID'] then in config/google.yml
- if !google_account_id.blank?
  :javascript
    var _gaq = [['_setAccount', '#{google_account_id}'], ['_trackPageview']];
    (function(d, t) {
     var g = d.createElement(t),
         s = d.getElementsByTagName(t)[0];
     g.async = true;
     g.src = ('https:' == location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
     s.parentNode.insertBefore(g, s);
    })(document, 'script');

app/views/layouts/_stylesheets.html.haml
-# CSS : implied media="all"
= stylesheet_link_tag 'style', :media => 'all'

-# Uncomment if you are specifically targeting less enabled mobile browsers
-#= stylesheet_link_tag 'handheld', :media => 'handheld'

-# Append your own using content_for :stylesheets
= yield :stylesheets

app/views/layouts/application.html.haml
!!! 5
-# http://paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither
-ie_html :lang => 'en', :class => 'no-js' do
  = render :partial => 'layouts/head'
  %body{ :class => "#{controller.controller_name}" }
    #container
      %header#header
        = render :partial => 'layouts/header'
      #main
        = render :partial => 'layouts/flashes'
        = yield
      %footer#footer
        = render :partial => 'layouts/footer'
    -# Javascript at the bottom for fast page loading
    = render :partial => 'layouts/javascripts'

app/views/users/shared/_links.haml
- if controller_name != 'sessions'
  = link_to "Sign in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.oauthable?
  - resource_class.oauth_providers.each do |provider|
    = link_to "Sign in with #{provider.to_s.titleize}", oauth_authorize_url(resource_name, provider)
    %br/